### ISSUE TITLE
Problem with GatewaySettings.bin on a F@st 3686 modem

### ISSUE THREAD

**Issue by perHub** [jclehner/bcm2-utils#17]
Hello, I'm trying to use bcm2cfg on a Fast3686 modem but it's a v2 CVA and the only output I'm getting is this:

./bcm2cfg -v info GatewaySettings.bin 
failed to remove padding
group size 0 too small to be valid
GatewaySettings.bin
type    : gwsettings
profile : fast3686
checksum: d46eca07a67cc93a820af19cdcdae88c (ok)
size    : 23632 (ok)
key     : 80

is this because the configuration encryption key is unknown and I should try to get it somehow and use it with the -k parameter? or is it because the Fast3686 profile is not compatible with my specific hardware version of the modem?

Thank you for the help.

**Comment by jclehner** [comment]
Please send me your GatewaySettings.bin file via email, and I'll see what I can do!

**Comment by perHub** [comment]
Hello, I sent it to your gmail address, I'm sorry if you already saw it but I'm getting sure because it could be in you spam folder or maybe you don't use that address anymore.

**Comment by bluckman** [comment]
Hello, thank you for all, I need user and password for log in, access telnet, file bin is crypted, here is please http://www.mediafire.com/file/7s9m0xrbqv7ys48/GatewaySettings.bin/file

**Comment by bluckman** [comment]
> Please send me your GatewaySettings.bin file via email, and I'll see what I can do!

I'm on facebook https://www.facebook.com/leonardo.leiva.71465

**Comment by jclehner** [comment]
@bluckman check out 65624ddad. In the future, please create another issue, instead of hijacking an old one. Closing this now.

<pre>
<code>
$ bcm2cfg get GatewaySettings.bin userif
userif = {
  http_user = "admin"
  http_pass = "s4g3mc0m"
  http_admin_user = "expert"
  http_admin_pass = "sagemcom97"
  http_local_user = "admin"
  http_local_pass = "blackman"
  http_default_pass = "admin"
  http_erouter_user = "admin"
  http_erouter_pass = "admin"
  remote_acc_methods = telnet | ssh
  <b>remote_acc_user = "admin"</b>
  <b>remote_acc_pass = "sagem"</b>
  telnet_ipstacks = IP1 | IP2 | IP5
  ssh_ipstacks = 0x00
  remote_acc_timeout = 600
  http_ipstacks = IP1 | IP2 | IP3 | IP5
  http_adv_ipstacks = IP3 | IP5
  http_seed = ""
  http_acl_hosts =
  http_idle_timeout = 600
  log_exceptions = yes
}
</code>
</pre>

**Comment by Leonardo0077** [comment]
Ohh, thanks  for your help, that's very nice of you, it work cool.

**Comment by pablino** [comment]
hi, how to enable telnet or ssh in my router sagemcom fast 3686?

¿
telnet_ipstacks = 0x00
  ssh_ipstacks = 0x00
  ?

userif = {
  http_user = "admin"
  http_pass = "admin"
  http_admin_user = "expert"
  http_admin_pass = "expert"
  http_local_user = "admin"
  http_local_pass = "admin"
  http_default_pass = "admin"
  http_erouter_user = "admin"
  http_erouter_pass = "admin"
  remote_acc_methods = 0x00
  remote_acc_user = "expert"
  telnet_ipstacks = 0x00
  ssh_ipstacks = 0x00
  remote_acc_timeout = 0
  http_ipstacks = 0x00
  http_adv_ipstacks = 0x00
  http_seed = ""
  http_acl_hosts =
  http_idle_timeout = 0
  log_exceptions = yes
}
